services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    environment:
      CLICKHOUSE_DB: tdms_data
      CLICKHOUSE_USER: tdms_user
      CLICKHOUSE_PASSWORD: password
    # Paramètres pour éviter les erreurs au démarrage
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
  clickhouse_logs: