version: "3.8"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # TCP native
    environment:
      CLICKHOUSE_DB: tdms_data
      CLICKHOUSE_USER: tdms_user
      CLICKHOUSE_PASSWORD: password
      # Optionnel: réduit un peu la verbosité
      # CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
  clickhouse_logs:
